- name: "Accessories"
  description: "Accessories"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - galculator
    - xfburn
- name: "Privacy"
  description: "Applications that ensure your privacy"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - tor-browser
    - tor
    - privoxy
- name: "Usb"
  description: "Usb writing applications"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - balena-etcher
    - imagewriter
- name: "Virtualisation"
  description: "Virtual machine software."
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - gnome-boxes
    - virtualbox

